version: '2'
services:
    cashcash-mysql:
        container_name: cashcash-mysql
        image: mysql:5.7.13
        environment:
              - MYSQL_RANDOM_ROOT_PASSWORD=yes
              - MYSQL_ONETIME_PASSWORD=yes
              - MYSQL_DATABASE=cashcash
              - MYSQL_USER=cashcashUser
              - MYSQL_PASSWORD=changeMe
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
