spring:
    datasource:
        url: jdbc:mysql://cashcash-mysql:3306/cashcash?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: cashcashUser
        password: changeme

    mail:
        host: smtp.gmail.com
        port: 587
        username: changeme
        password: changeme
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com