spring:
    datasource:
        url: jdbc:mysql://cashcash-mysql:3306/cashcash?useUnicode=true&characterEncoding=utf8&useSSL=false
        hikari:
          username: cashcashUser
          password: changeMe
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: changeme
        password: changeme
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com