package com.gagnepain.cashcash.repository.custom.annotation;

import org.hibernate.tuple.AnnotationValueGeneration;
import org.hibernate.tuple.GenerationTiming;
import org.hibernate.tuple.ValueGenerator;

public class FunctionUpdateValueGeneration implements AnnotationValueGeneration<FunctionUpdateTimestamp> {
	private ValueGenerator<?> generator;

	@Override
	public void initialize(final FunctionUpdateTimestamp annotation, final Class<?> propertyType) {
		generator = new CurrentZonedDateTimeGenerator();
	}

	/**
	 * Generate value on ALWAYS
	 *
	 * @return when to generate the value
	 */
	public GenerationTiming getGenerationTiming() {
		return GenerationTiming.ALWAYS;
	}

	/**
	 * Returns the generator
	 *
	 * @return null
	 */
	public ValueGenerator<?> getValueGenerator() {
		return generator;
	}

	/**
	 * Returns false because the value is generated by the JVM.
	 *
	 * @return false
	 */
	public boolean referenceColumnInSql() {
		return false;
	}

	/**
	 * Returns null
	 *
	 * @return null
	 */
	public String getDatabaseGeneratedReferencedColumnValue() {
		return null;
	}
}
